// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/kidtube/Grid.tsx": () => import("../components/mockups/kidtube/Grid.tsx"),
  "./components/mockups/kidtube/Manage.tsx": () => import("../components/mockups/kidtube/Manage.tsx"),
  "./components/mockups/kidtube/Player.tsx": () => import("../components/mockups/kidtube/Player.tsx")
};
